export const ACADEMY_STRUCTURE = [
  {
    key: 'xueya',
    label: '學雅',
    chapters: [
      { id: '01', title: '茶之於味：當代茶道的藝術與哲學精神' },
      { id: '02', title: '' },
      { id: '03', title: '儀軌教學 / 茶荷置茶法' },
      { id: '04', title: '人文茶道儀軌' },
      { id: '05', title: '凍頂烏龍茶深度解析' },
      { id: '06', title: '鐵觀音' },
      { id: '07', title: '蓋杯 / 紅烏龍' },
      { id: '08', title: '茶則置茶 / 坪林包種茶' },
      { id: '09', title: '東方美人' },
      { id: '10', title: '做紅茶' },
      { id: '11', title: '紅茶：小葉紅 / 大葉紅' },
      { id: '12', title: '學雅茶湯會' },
    ],
    prefix: '?tab=academy_xueya_',
  },
  {
    key: 'zhiya',
    label: '質雅',
    chapters: [
      { id: '01', title: '紅烏龍 / 懸空置茶法' },
      { id: '02', title: '品味討論 清香形' },
      { id: '03', title: '品味討論 焙香形' },
      { id: '04', title: '品味討論 濃香形' },
      { id: '05', title: '茶席設計與雙杯品鑑' },
      { id: '06', title: '茶席設計美學：佈局/用色/意境' },
      { id: '07', title: '茶席/器物之選/色彩密碼' },
      { id: '08', title: '茶會觀摩學習 / 大桶茶泡法' },
      { id: '09', title: '茶道進階與西湖龍井品鑑' },
      { id: '10', title: '茶碗以匙分茶 / 碧螺春 / 武夷岩茶' },
      { id: '11', title: '普洱茶' },
      { id: '12', title: '武夷岩茶沖泡' },
      { id: '13', title: '白茶沖泡' },
      { id: '14', title: '紅茶' },
      { id: '15', title: '茶會的舉辦與練習' },
      { id: '16', title: '茶會的舉辦：清香渡荷來' },
    ],
    prefix: '?tab=academy_zhiya_',
  },
  {
    key: 'chonghua',
    label: '崇華',
    chapters: [
      { id: '01', title: '茶具的佈置與搭配' },
      { id: '02', title: '茶席儀軌' },
      { id: '03', title: '世界與台灣紅茶史' },
      { id: '04', title: '開啟你的風味冒險地圖' },
      { id: '05', title: '第05堂' },
      { id: '06', title: '認識茶樹品種' },
      { id: '07', title: '青茶類風味辨識' },
      { id: '08', title: '紅茶類風味辨識' },
      { id: '09', title: '認識氧化' },
      { id: '10', title: '第10堂' },
      { id: '11', title: '第11堂' },
      { id: '12', title: '第12堂' },
      { id: '13', title: '第13堂' },
      { id: '14', title: '第14堂' },
      { id: '15', title: '第15堂' },
      { id: '16', title: '第16堂' },
      { id: '17', title: '第17堂' },
      { id: '18', title: '第18堂' },
      { id: '19', title: '第19堂' },
      { id: '20', title: '第20堂' },
      { id: '21', title: '第21堂' },
      { id: '22', title: '第22堂' },
      { id: '23', title: '第23堂' },
      { id: '24', title: '第24堂' },
      { id: '25', title: '第25堂' },
      { id: '26', title: '第26堂' },
      { id: '27', title: '第27堂' },
      { id: '28', title: '第28堂' },
      { id: '29', title: '第29堂' },
      { id: '30', title: '第30堂' },
      { id: '31', title: '第31堂' },
      { id: '32', title: '第32堂' },
      { id: '33', title: '第33堂' },
    ],
    prefix: '?tab=academy_chonghua_',
  },
];



