export const PRIMARY_SITE_NAV = [
  {
    id: 'learn',
    label: '開始學習',
    labelEn: 'Start Here',
    currentTab: 'journey',
    canonicalPath: '/learn',
    eyebrow: 'Learning Path',
    eyebrowEn: 'Learning Path',
    description: '從主題搜尋、路線建議與快速入口開始。',
    descriptionEn: 'Begin with topic search, learning routes, and quick entry points.',
    children: [],
  },
  {
    id: 'encyclopedia',
    label: '茶學百科',
    labelEn: 'Tea Encyclopedia',
    currentTab: 'varieties',
    canonicalPath: '/encyclopedia',
    eyebrow: 'Knowledge Base',
    eyebrowEn: 'Knowledge Base',
    description: '茶類、科學、器物與歷史的資料庫型索引。',
    descriptionEn: 'A database-style index for tea types, science, teaware, and history.',
    children: [
      {
        id: 'tea-types',
        label: '六大茶類',
        labelEn: 'Six Tea Types',
        description: '綠、黃、白、青、紅、黑茶的分類與製程。',
        descriptionEn: 'Classification and processing of green, yellow, white, oolong, black, and dark teas.',
        currentTab: 'varieties',
        canonicalPath: '/encyclopedia/tea-types',
      },
      {
        id: 'puerh',
        label: '普洱茶',
        labelEn: 'Pu-erh Tea',
        description: '普洱生茶、熟茶、陳化與雲南茶文化。',
        descriptionEn: 'Raw and ripe Pu-erh, aging, and Yunnan tea culture.',
        currentTab: 'puerh',
        canonicalPath: '/encyclopedia/puerh',
      },
      {
        id: 'science',
        label: '茶葉科學',
        labelEn: 'Tea Science',
        description: '成分、香氣、氧化、烘焙與農殘主題。',
        descriptionEn: 'Compounds, aroma, oxidation, roasting, and pesticide topics.',
        currentTab: 'science',
        canonicalPath: '/encyclopedia/science',
      },
      {
        id: 'tea-talk',
        label: '茶言觀色',
        labelEn: 'Tea Palette',
        description: '用色彩與語彙整理茶湯感受。',
        descriptionEn: 'Map tea liquor impressions with color and sensory language.',
        currentTab: 'tea_talk',
        canonicalPath: '/practice/tea-palette',
      },
      {
        id: 'zisha',
        label: '紫砂茶具',
        labelEn: 'Zisha Teaware',
        description: '紫砂泥料、器型、工藝與鑑賞。',
        descriptionEn: 'Zisha clay, forms, craft, and appreciation.',
        currentTab: 'zisha',
        canonicalPath: '/encyclopedia/teaware/zisha',
      },
      {
        id: 'history',
        label: '歷史文化',
        labelEn: 'History & Culture',
        description: '中國茶史、台灣茶業與茶事年表。',
        descriptionEn: 'Chinese tea history, Taiwan tea industry, and tea timelines.',
        currentTab: 'history',
        canonicalPath: '/encyclopedia/history',
      },
    ],
  },
  {
    id: 'taiwan-tea',
    label: '台灣茶',
    labelEn: 'Taiwan Tea',
    currentTab: 'featured',
    canonicalPath: '/taiwan-tea',
    eyebrow: 'Taiwan Tea',
    eyebrowEn: 'Taiwan Tea',
    description: '台灣特色茶、產區、品種與季節專題。',
    descriptionEn: 'Taiwan specialties, regions, cultivars, and seasonal themes.',
    children: [
      {
        id: 'featured',
        label: '台灣特色茶',
        labelEn: 'Taiwan Specialties',
        description: '包種、凍頂、東方美人、蜜香紅茶等專題。',
        descriptionEn: 'Baozhong, Dong Ding, Oriental Beauty, honey black tea, and more.',
        currentTab: 'featured',
        canonicalPath: '/taiwan-tea/featured',
      },
      {
        id: 'regions',
        label: '產區導覽',
        labelEn: 'Tea Regions',
        description: '以地理與風土理解台灣茶區。',
        descriptionEn: 'Understand Taiwan tea regions through geography and terroir.',
        currentTab: 'regions',
        canonicalPath: '/taiwan-tea/regions',
      },
      {
        id: 'cultivars',
        label: '台灣茶樹品種',
        labelEn: 'Taiwan Cultivars',
        description: '台茶品種、適製性與品種差異。',
        descriptionEn: 'Taiwan cultivars, processing suitability, and variety differences.',
        currentTab: 'cultivars',
        canonicalPath: '/taiwan-tea/cultivars',
      },
      {
        id: 'seasons',
        label: '季節採收',
        labelEn: 'Seasonal Harvests',
        description: '四季茶與二十四節氣的採收節奏。',
        descriptionEn: 'Seasonal tea harvests and the rhythm of the 24 solar terms.',
        currentTab: 'seasons',
        canonicalPath: '/taiwan-tea/seasons',
      },
    ],
  },
  {
    id: 'courses',
    label: '課程',
    labelEn: 'Courses',
    currentTab: 'course',
    canonicalPath: '/courses',
    eyebrow: 'Courses',
    eyebrowEn: 'Courses',
    description: '課綱、教案、課堂活動與測驗。',
    descriptionEn: 'Syllabi, lesson plans, classroom activities, and quizzes.',
    children: [],
  },
  {
    id: 'tools',
    label: '實作 / 互動',
    labelEn: 'Practice / Tools',
    currentTab: 'brewing',
    canonicalPath: '/practice',
    eyebrow: 'Practice Studio',
    eyebrowEn: 'Practice Studio',
    description: '操作型教學、品評練習與互動工具。',
    descriptionEn: 'Hands-on teaching, sensory drills, and interactive tools.',
    children: [
      {
        id: 'brewing',
        label: '沖泡入門',
        labelEn: 'Brewing Basics',
        description: '水溫、比例、器具與風味調整。',
        descriptionEn: 'Water temperature, ratios, teaware, and flavor adjustment.',
        currentTab: 'brewing',
        canonicalPath: '/practice/brewing',
      },
      {
        id: 'ceremony',
        label: '茶席入門',
        labelEn: 'Tea Setting Basics',
        description: '茶席配置、器具選用與奉茶禮儀。',
        descriptionEn: 'Tea setting layout, teaware choices, and serving etiquette.',
        currentTab: 'ceremony',
        canonicalPath: '/practice/tea-ceremony',
      },
      {
        id: 'sensory',
        label: '品評考題',
        labelEn: 'Sensory Quiz',
        description: '以題庫練習香氣、滋味與感官判讀。',
        descriptionEn: 'Practice aroma, taste, and sensory judgment with quiz prompts.',
        currentTab: 'sensory',
        canonicalPath: '/practice/sensory-quiz',
      },
    ],
  },
  {
    id: 'resources',
    label: '影片',
    labelEn: 'Videos',
    currentTab: 'video',
    canonicalPath: '/videos',
    eyebrow: 'Media Library',
    eyebrowEn: 'Media Library',
    description: '茶學放映室與影音內容。',
    descriptionEn: 'Tea video library and media resources.',
    children: [],
  },
];

export const HOME_AUDIENCE_PATHS = [
  {
    id: 'beginner',
    label: '我是初學者',
    description: '從茶類分類、風味與沖泡基礎開始。',
    currentTab: 'journey',
    canonicalPath: '/learn/beginner',
  },
  {
    id: 'researcher',
    label: '我要查資料',
    description: '進入百科索引，查找茶類、製程、產區與歷史。',
    currentTab: 'varieties',
    canonicalPath: '/encyclopedia',
  },
  {
    id: 'teacher',
    label: '我要備課 / 上課',
    description: '查看課程設計、活動素材與教學章節。',
    currentTab: 'course',
    canonicalPath: '/courses',
  },
];

export const CANONICAL_ROUTE_ALIASES = {
  journey: '/',
  home: '/',
  varieties: '/encyclopedia/tea-types',
  puerh: '/encyclopedia/puerh',
  cultivars: '/taiwan-tea/cultivars',
  science: '/encyclopedia/science',
  brewing: '/practice/brewing',
  featured: '/taiwan-tea/featured',
  seasons: '/taiwan-tea/seasons',
  ceremony: '/practice/tea-ceremony',
  zisha: '/encyclopedia/teaware/zisha',
  regions: '/taiwan-tea/regions',
  history: '/encyclopedia/history',
  sensory: '/practice/sensory-quiz',
  tea_talk: '/practice/tea-palette',
  video: '/videos',
  course: '/courses',
};
